monitor_devices:
    - Display:
        name: display
        reporting_unit_type: pix
        device_number: 0
        physical_dimensions:
            width: 531.9
            height: 299.2
            unit_type: mm
        default_eye_distance:
            surface_center: 700
            unit_type: mm
        origin: center