monitor_devices:
    - Display:
        name: display
        reporting_unit_type: pix
        device_number: 1
        physical_dimensions:
            width: 473.76
            height: 296.1
            unit_type: mm
            #pixel_size = 0.282
        default_eye_distance:
            surface_center: 600
            unit_type: mm
        origin: center