monitor_devices:
    - Display:
        name: display
        reporting_unit_type: pix
        device_number: 1
        physical_dimensions:
            width: 508.8
            height: 286.2
            unit_type: mm
        default_eye_distance:
            surface_center: 600
            unit_type: mm
        origin: center
